=pod

Find out more about OpenStreetMap's upcoming license change
(http://www.osmfoundation.org/wiki/License/We_Are_Changing_The_License)
(translations
(http://wiki.openstreetmap.org/wiki/ODbL/We_Are_Changing_The_License))
(discussion (http://wiki.openstreetmap.org/wiki/Talk:ODbL/Upcoming))

=head1 API v0.6

=head2 From OpenStreetMap Wiki

Jump to: navigation
(http://wiki.openstreetmap.org/wiki/API_v0.6#mw-head), search
(http://wiki.openstreetmap.org/wiki/API_v0.6#p-search)

Help (http://wiki.openstreetmap.org/wiki/Wiki_Translation)

B<Available languages>

E<acirc>E<128>E<cent> B<English> E<acirc>E<128>E<cent>
PortuguE<Atilde>E<ordf>s do Brasil
(http://wiki.openstreetmap.org/wiki/Pt-br:API_v0.6)
E<acirc>E<128>E<cent> E<ETH>
E<Ntilde>E<131>E<Ntilde>E<129>E<Ntilde>E<129>E<ETH>E<ordm>E<ETH>E<cedil>E<ETH>E<sup1>
(http://wiki.openstreetmap.org/wiki/RU:API_v0.6)

show (http://wiki.openstreetmap.org/wiki/API_v0.6#)

B<Missing languages>

E<acirc>E<128>E<cent> E<aacute>E<138>
E<aacute>E<136>E<155>E<aacute>E<136>E<shy>E<aacute>E<138>E<155>
(http://wiki.openstreetmap.org/w/index.php?title=Am:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<Oslash>E<sect>E<Ugrave>E<132>E<Oslash>E<sup1>E<Oslash>E<plusmn>E<Oslash>E<uml>E<Ugrave>E<138>E<Oslash>E<copy>
(http://wiki.openstreetmap.org/w/index.php?title=Ar:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<ETH>E<145>E<Ntilde>E<138>E<ETH>E<rchevron>E<ETH>E<sup3>E<ETH>E<deg>E<Ntilde>E<128>E<Ntilde>E<129>E<ETH>E<ordm>E<ETH>E<cedil>
(http://wiki.openstreetmap.org/w/index.php?title=Bg:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Brezhoneg
(http://wiki.openstreetmap.org/w/index.php?title=Br:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Bosanski
(http://wiki.openstreetmap.org/w/index.php?title=Bs:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> CatalE<Atilde>
(http://wiki.openstreetmap.org/w/index.php?title=Ca:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> E<Auml>E<140>esky
(http://wiki.openstreetmap.org/w/index.php?title=Cz:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Dansk
(http://wiki.openstreetmap.org/w/index.php?title=Da:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Deutsch
(http://wiki.openstreetmap.org/w/index.php?title=DE:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<Icirc>E<149>E<Icirc>E<rchevron>E<Icirc>E<rchevron>E<Icirc>E<middot>E<Icirc>E<frac12>E<Icirc>E<sup1>E<Icirc>E<ordm>E<Icirc>E<not>
(http://wiki.openstreetmap.org/w/index.php?title=El:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Esperanto
(http://wiki.openstreetmap.org/w/index.php?title=Eo:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> EspaE<Atilde>E<plusmn>ol
(http://wiki.openstreetmap.org/w/index.php?title=ES:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Eesti
(http://wiki.openstreetmap.org/w/index.php?title=Et:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Euskara
(http://wiki.openstreetmap.org/w/index.php?title=Eu:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Suomi
(http://wiki.openstreetmap.org/w/index.php?title=Fi:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> FranE<Atilde>E<sect>ais
(http://wiki.openstreetmap.org/w/index.php?title=FR:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Frysk
(http://wiki.openstreetmap.org/w/index.php?title=Fy:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> CrE<Atilde>E<copy>ole guadeloupE<Atilde>E<copy>en
(http://wiki.openstreetmap.org/w/index.php?title=Gcf:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<times>E<cent>E<times>E<145>E<times>E<uml>E<times>E<153>E<times>E<ordf>
(http://wiki.openstreetmap.org/w/index.php?title=He:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Hrvatski
(http://wiki.openstreetmap.org/w/index.php?title=Hr:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Magyar
(http://wiki.openstreetmap.org/w/index.php?title=HU:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<Otilde>E<128>E<Otilde>E<iexcl>E<Otilde>E<micro>E<Otilde>E<yen>E<Ouml>E<128>E<Otilde>E<yen>E<Otilde>E<para>
(http://wiki.openstreetmap.org/w/index.php?title=Hy:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Interlingua
(http://wiki.openstreetmap.org/w/index.php?title=Ia:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> E<Atilde>E<141>slenska
(http://wiki.openstreetmap.org/w/index.php?title=Is:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Italiano
(http://wiki.openstreetmap.org/w/index.php?title=IT:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<aelig>E<151>E<yen>E<aelig>E<156>E<not>E<egrave>E<ordf>E<158>
(http://wiki.openstreetmap.org/w/index.php?title=JA:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<iacute>E<149>E<156>E<ecirc>E<micro>E<shy>E<igrave>E<150>E<acute>
(http://wiki.openstreetmap.org/w/index.php?title=Ko:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> LE<Atilde>E<lchevron>tzebuergesch
(http://wiki.openstreetmap.org/w/index.php?title=Lb:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> LietuviE<Aring>E<sup3>
(http://wiki.openstreetmap.org/w/index.php?title=Lt:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> LatvieE<Aring>E<iexcl>u
(http://wiki.openstreetmap.org/w/index.php?title=Lv:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<ETH>E<156>E<ETH>E<deg>E<ETH>E<ordm>E<ETH>E<micro>E<ETH>E<acute>E<ETH>E<frac34>E<ETH>E<frac12>E<Ntilde>E<129>E<ETH>E<ordm>E<ETH>E<cedil>
(http://wiki.openstreetmap.org/w/index.php?title=Mk:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Nederlands
(http://wiki.openstreetmap.org/w/index.php?title=NL:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> E<acirc>E<128>E<ordf>Norsk
(nynorsk)E<acirc>E<128>E<not>
(http://wiki.openstreetmap.org/w/index.php?title=Nn:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> E<acirc>E<128>E<ordf>Norsk
(bokmE<Atilde>E<yen>l)E<acirc>E<128>E<not>
(http://wiki.openstreetmap.org/w/index.php?title=No:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Polski
(http://wiki.openstreetmap.org/w/index.php?title=Pl:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> PortuguE<Atilde>E<ordf>s
(http://wiki.openstreetmap.org/w/index.php?title=Pt:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> RomE<Atilde>E<cent>nE<Auml>E<131>
(http://wiki.openstreetmap.org/w/index.php?title=Ro:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> RomE<Atilde>E<cent>nE<Auml>E<131> (Moldova)
(http://wiki.openstreetmap.org/w/index.php?title=Ro-md:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> SlovenE<Auml>E<141>ina
(http://wiki.openstreetmap.org/w/index.php?title=Sk:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> SlovenE<Aring>E<iexcl>E<Auml>E<141>ina
(http://wiki.openstreetmap.org/w/index.php?title=Sl:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Shqip
(http://wiki.openstreetmap.org/w/index.php?title=Sq:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> Svenska
(http://wiki.openstreetmap.org/w/index.php?title=Sv:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> TE<Atilde>E<frac14>rkE<Atilde>E<sect>e
(http://wiki.openstreetmap.org/w/index.php?title=Tr:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<ETH>E<pound>E<ETH>E<ordm>E<Ntilde>E<128>E<ETH>E<deg>E<Ntilde>E<151>E<ETH>E<frac12>E<Ntilde>E<129>E<Ntilde>E<140>E<ETH>E<ordm>E<ETH>E<deg>
(http://wiki.openstreetmap.org/w/index.php?title=Uk:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent> TiE<aacute>E<ordm>E<iquest>ng
ViE<aacute>E<rchevron>E<135>t
(http://wiki.openstreetmap.org/w/index.php?title=Vi:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<acirc>E<128>E<ordf>E<auml>E<cedil>E<shy>E<aelig>E<150>E<135>(E<ccedil>E<reg>E<128>E<auml>E<frac12>E<147>)E<acirc>E<128>E<not>
(http://wiki.openstreetmap.org/w/index.php?title=Zh-hans:API_v0.6&action=edit&redlink=1)
E<acirc>E<128>E<cent>
E<acirc>E<128>E<ordf>E<auml>E<cedil>E<shy>E<aelig>E<150>E<135>(E<ccedil>E<sup1>E<129>E<eacute>E<lchevron>E<148>)E<acirc>E<128>E<not>
(http://wiki.openstreetmap.org/w/index.php?title=Zh-hant:API_v0.6&action=edit&redlink=1)

show (http://wiki.openstreetmap.org/wiki/API_v0.6#)

B<API v0.6> is the I<current> version of the OSM API
(http://wiki.openstreetmap.org/wiki/API) deployed 17-21 April 2009.

=head2 Contents

[hide (javascript:toggleToc())]

=over

=item * 1 General information
(http://wiki.openstreetmap.org/wiki/API_v0.6#General_information)

=over

=item * 1.1 URL + Authentication
(http://wiki.openstreetmap.org/wiki/API_v0.6#URL_.2B_Authentication)

=item * 1.2 Elements
(http://wiki.openstreetmap.org/wiki/API_v0.6#Elements)

=item * 1.3 Changesets
(http://wiki.openstreetmap.org/wiki/API_v0.6#Changesets)

=item * 1.4 Tags (http://wiki.openstreetmap.org/wiki/API_v0.6#Tags)

=item * 1.5 Reliably identifying users
(http://wiki.openstreetmap.org/wiki/API_v0.6#Reliably_identifying_users)

=item * 1.6 Version numbers/Optimistic locking
(http://wiki.openstreetmap.org/wiki/API_v0.6#Version_numbers.2FOptimistic_locking)

=item * 1.7 XML Format
(http://wiki.openstreetmap.org/wiki/API_v0.6#XML_Format)

=item * 1.8 Faking the correct HTTP methods
(http://wiki.openstreetmap.org/wiki/API_v0.6#Faking_the_correct_HTTP_methods)

=back

=item * 2 API calls
(http://wiki.openstreetmap.org/wiki/API_v0.6#API_calls)

=over

=item * 2.1 Miscellaneous
(http://wiki.openstreetmap.org/wiki/API_v0.6#Miscellaneous)

=over

=item * 2.1.1 Capabilities: GET /api/capabilities
(http://wiki.openstreetmap.org/wiki/API_v0.6#Capabilities:_GET_.2Fapi.2Fcapabilities)

=over

=item * 2.1.1.1 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response)

=item * 2.1.1.2 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes)

=back

=item * 2.1.2 Retrieving map data by bounding box: GET /api/0.6/map
(http://wiki.openstreetmap.org/wiki/API_v0.6#Retrieving_map_data_by_bounding_box:_GET_.2Fapi.2F0.6.2Fmap)

=over

=item * 2.1.2.1 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes)

=back

=back

=item * 2.2 Changesets
(http://wiki.openstreetmap.org/wiki/API_v0.6#Changesets_2)

=over

=item * 2.2.1 Bounding box computation
(http://wiki.openstreetmap.org/wiki/API_v0.6#Bounding_box_computation)

=item * 2.2.2 Create: PUT /api/0.6/changeset/create
(http://wiki.openstreetmap.org/wiki/API_v0.6#Create:_PUT_.2Fapi.2F0.6.2Fchangeset.2Fcreate)

=over

=item * 2.2.2.1 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_2)

=item * 2.2.2.2 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_2)

=item * 2.2.2.3 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_2)

=back

=item * 2.2.3 Read: GET /api/0.6/changeset/#id
(http://wiki.openstreetmap.org/wiki/API_v0.6#Read:_GET_.2Fapi.2F0.6.2Fchangeset.2F.23id)

=over

=item * 2.2.3.1 Parameters
(http://wiki.openstreetmap.org/wiki/API_v0.6#Parameters)

=item * 2.2.3.2 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_3)

=item * 2.2.3.3 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_3)

=item * 2.2.3.4 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_3)

=back

=item * 2.2.4 Update: PUT /api/0.6/changeset/#id
(http://wiki.openstreetmap.org/wiki/API_v0.6#Update:_PUT_.2Fapi.2F0.6.2Fchangeset.2F.23id)

=over

=item * 2.2.4.1 Parameters
(http://wiki.openstreetmap.org/wiki/API_v0.6#Parameters_2)

=item * 2.2.4.2 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_4)

=item * 2.2.4.3 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_4)

=item * 2.2.4.4 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_4)

=back

=item * 2.2.5 Close: PUT /api/0.6/changeset/#id/close
(http://wiki.openstreetmap.org/wiki/API_v0.6#Close:_PUT_.2Fapi.2F0.6.2Fchangeset.2F.23id.2Fclose)

=over

=item * 2.2.5.1 Parameters
(http://wiki.openstreetmap.org/wiki/API_v0.6#Parameters_3)

=item * 2.2.5.2 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_5)

=item * 2.2.5.3 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_5)

=back

=item * 2.2.6 Download: GET /api/0.6/changeset/#id/download
(http://wiki.openstreetmap.org/wiki/API_v0.6#Download:_GET_.2Fapi.2F0.6.2Fchangeset.2F.23id.2Fdownload)

=over

=item * 2.2.6.1 Parameters
(http://wiki.openstreetmap.org/wiki/API_v0.6#Parameters_4)

=item * 2.2.6.2 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_6)

=item * 2.2.6.3 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_6)

=item * 2.2.6.4 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_5)

=back

=item * 2.2.7 Expand Bounding Box: POST
/api/0.6/changeset/#id/expand_bbox
(http://wiki.openstreetmap.org/wiki/API_v0.6#Expand_Bounding_Box:_POST_.2Fapi.2F0.6.2Fchangeset.2F.23id.2Fexpand_bbox)

=over

=item * 2.2.7.1 Parameters
(http://wiki.openstreetmap.org/wiki/API_v0.6#Parameters_5)

=item * 2.2.7.2 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_7)

=item * 2.2.7.3 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_7)

=item * 2.2.7.4 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_6)

=back

=item * 2.2.8 Query: GET /api/0.6/changesets
(http://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets)

=over

=item * 2.2.8.1 Parameters
(http://wiki.openstreetmap.org/wiki/API_v0.6#Parameters_6)

=item * 2.2.8.2 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_8)

=item * 2.2.8.3 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_8)

=item * 2.2.8.4 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_7)

=back

=item * 2.2.9 Diff upload: POST /api/0.6/changeset/#id/upload

=over

=item * 2.2.9.1 Parameters
(http://wiki.openstreetmap.org/wiki/API_v0.6#Parameters_7)

=item * 2.2.9.2 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_9)

=item * 2.2.9.3 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_9)

=item * 2.2.9.4 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_8)

=back

=item * 2.2.10 Changeset summary
(http://wiki.openstreetmap.org/wiki/API_v0.6#Changeset_summary)

=back

=item * 2.3 Elements
(http://wiki.openstreetmap.org/wiki/API_v0.6#Elements_2)

=over

=item * 2.3.1 Create: PUT /api/0.6/[node|way|relation]/create
(http://wiki.openstreetmap.org/wiki/API_v0.6#Create:_PUT_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2Fcreate)

=over

=item * 2.3.1.1 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_10)

=item * 2.3.1.2 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_10)

=item * 2.3.1.3 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_9)

=back

=item * 2.3.2 Read: GET /api/0.6/[node|way|relation]/#id
(http://wiki.openstreetmap.org/wiki/API_v0.6#Read:_GET_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id)

=over

=item * 2.3.2.1 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_11)

=item * 2.3.2.2 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_11)

=back

=item * 2.3.3 Update: PUT /api/0.6/[node|way|relation]/#id
(http://wiki.openstreetmap.org/wiki/API_v0.6#Update:_PUT_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id)

=over

=item * 2.3.3.1 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_12)

=item * 2.3.3.2 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_12)

=item * 2.3.3.3 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_10)

=back

=item * 2.3.4 Delete: DELETE /api/0.6/[node|way|relation]/#id
(http://wiki.openstreetmap.org/wiki/API_v0.6#Delete:_DELETE_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id)

=over

=item * 2.3.4.1 Response
(http://wiki.openstreetmap.org/wiki/API_v0.6#Response_13)

=item * 2.3.4.2 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_13)

=item * 2.3.4.3 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_11)

=back

=item * 2.3.5 History: GET /api/0.6/[node|way|relation]/#id/history
(http://wiki.openstreetmap.org/wiki/API_v0.6#History:_GET_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id.2Fhistory)

=over

=item * 2.3.5.1 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_14)

=back

=item * 2.3.6 Version: GET /api/0.6/[node|way|relation]/#id/#version
(http://wiki.openstreetmap.org/wiki/API_v0.6#Version:_GET_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id.2F.23version)

=over

=item * 2.3.6.1 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_15)

=back

=item * 2.3.7 Multi fetch: GET /api/0.6/[nodes|ways|relations]
(http://wiki.openstreetmap.org/wiki/API_v0.6#Multi_fetch:_GET_.2Fapi.2F0.6.2F.5Bnodes.7Cways.7Crelations.5D)

=over

=item * 2.3.7.1 Parameters
(http://wiki.openstreetmap.org/wiki/API_v0.6#Parameters_8)

=item * 2.3.7.2 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_16)

=back

=item * 2.3.8 Relations for Element: GET
/api/0.6/[node|way|relation]/#id/relations
(http://wiki.openstreetmap.org/wiki/API_v0.6#Relations_for_Element:_GET_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id.2Frelations)

=over

=item * 2.3.8.1 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_12)

=back

=item * 2.3.9 Ways for Node: GET /api/0.6/node/#id/ways
(http://wiki.openstreetmap.org/wiki/API_v0.6#Ways_for_Node:_GET_.2Fapi.2F0.6.2Fnode.2F.23id.2Fways)

=over

=item * 2.3.9.1 Notes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Notes_13)

=back

=item * 2.3.10 Full: GET /api/0.6/[way|relation]/#id/full
(http://wiki.openstreetmap.org/wiki/API_v0.6#Full:_GET_.2Fapi.2F0.6.2F.5Bway.7Crelation.5D.2F.23id.2Ffull)

=over

=item * 2.3.10.1 Error codes
(http://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_17)

=back

=back

=item * 2.4 GPS Traces
(http://wiki.openstreetmap.org/wiki/API_v0.6#GPS_Traces)

=over

=item * 2.4.1 Retrieving GPS points
(http://wiki.openstreetmap.org/wiki/API_v0.6#Retrieving_GPS_points)

=over

=item * 2.4.1.1 Examples
(http://wiki.openstreetmap.org/wiki/API_v0.6#Examples)

=back

=item * 2.4.2 Uploading Traces
(http://wiki.openstreetmap.org/wiki/API_v0.6#Uploading_Traces)

=item * 2.4.3 Downloading Trace Metadata
(http://wiki.openstreetmap.org/wiki/API_v0.6#Downloading_Trace_Metadata)

=back

=item * 2.5 Methods for User Data
(http://wiki.openstreetmap.org/wiki/API_v0.6#Methods_for_User_Data)

=over

=item * 2.5.1 Details
(http://wiki.openstreetmap.org/wiki/API_v0.6#Details)

=item * 2.5.2 Preferences
(http://wiki.openstreetmap.org/wiki/API_v0.6#Preferences)

=back

=back

=item * 3 When NOT to use the API
(http://wiki.openstreetmap.org/wiki/API_v0.6#When_NOT_to_use_the_API)

=item * 4 Further Reading
(http://wiki.openstreetmap.org/wiki/API_v0.6#Further_Reading)

=back

=head1 General information

This API is based on the ideas of the RESTful API. For more information
on RESTful APIs see wikipedia's Representational State Transfer page
(http://en.wikipedia.org/wiki/Representational_State_Transfer).

The API is the server component to which REST requests are addressed.
The REST requests take the form of HTTP GET, PUT, POST, and DELETE
messages. Any payload is in XML form, using the MIME type "text/xml"
and UTF-8 character encoding, and may be compressed on the HTTP layer
if the client indicates through the HTTP "Accept" header that it can
handle compressed messages.

Requests to modify the database are authorized using I<HTTP Basic
Authorization> or I<OAuth (http://wiki.openstreetmap.org/wiki/OAuth)>.
Read requests do not require authorization (except user details).

Preliminary Full DTD
(http://wiki.openstreetmap.org/wiki/OSM_Protocol_Version_0.6/DTD)
(under construction and discussion).

Changes between API v0.5 and API v0.6
(http://wiki.openstreetmap.org/wiki/OSM_Protocol_Changes_V0.5_to_V0.6)

=head2 URL + Authentication

The API is currently accessible using the following URL:
B<http://api.openstreetmap.org/ (http://api.openstreetmap.org/)>

If you want to test your software against the API you should consider
using B<http://api06.dev.openstreetmap.org/
(http://api06.dev.openstreetmap.org/)> instead of the live-api.

All of the calls to the API which update, create or delete data have to
be made by an authenticated and authorized user. Authentication works
by using HTTP Basic authentication using an user name and password or
by using OAuth (http://wiki.openstreetmap.org/wiki/OAuth).

=head2 Elements

There are API calls to create, read, update and delete the three basic
elements (http://wiki.openstreetmap.org/wiki/Elements) that make up the
map data for OpenStreetMap. They each return or expect the data for the
elements in a XML format.

=head2 Changesets

Every modification of one or more of the elements has to reference an
open changeset
(http://wiki.openstreetmap.org/wiki/API_v0.6#Changesets_2).

=head2 Tags

Every element and changeset may have any number of tags. A tag is a
Key-Value pair of Unicode strings of up to 255 characters (full Unicode
characters, not bytes).

=head2 Reliably identifying users

The previous API v0.5 returned only the user display name. The user can
update this at any time and there is no history stored for display name
changes. This means there was no way to reliably identify which user
made a specific change. API v0.6 includes the numeric user ID of the
account in addition to the display name. e.g.

 <node id="68" ... user="fred" uid="123"/>

This still requires the user to have made his edits public. User ID for
users who have previously made anonymous changes will not be visible.
In accordance with a recommendation from the OpenStreetMap Foundation
Board, anonymous edits
(http://wiki.openstreetmap.org/wiki/Anonymous_edits) are no longer be
allowed.

=head2 Version numbers/Optimistic locking

The planet dump, diffs and the API calls for elements will return a
I<version> attribute for each I<Node>, I<Way> and I<Relation>.

 <node id="68" ... version="12"/>

These version numbers are used for I<optimistic locking>. To upload a
new version of an object, the client will need to provide the version
of the object it is modifying. If the version supplied is not the same
as the server's current version, an error will be returned (HTTP status
code 409: Conflict). This means that any client that is updating data
will need to save the version numbers of the original data. One element
can be updated multiple times during one changeset and its version
number is increased each time so there can be multiple I<history
versions> of a single element for one changeset.

In addition, clients can now ask for specific versions of an element.

Version numbers will always begin at I<1> and increase by 1 every time
an element is changed. Clients should not, however, rely on the
increase by 1 when updating an element, but instead retrieve the new
version number from the server response.

=head2 XML Format

Every XML response from the server is wrapped in an C<E<lt>osmE<gt>>
element unless specified otherwise (e.g. for diff uploads, or changeset
downloads). In most of the later examples this wrapper is left out.

 <osm version="0.6" generator="OpenStreetMap server">
   ...
   ...
 </osm>

Every call to the API has to be wrapped in an C<E<lt>osmE<gt>> element
as well but the I<version> and I<generator> attributes can be left out.

=head2 Faking the correct HTTP methods

Many of the API calls use PUT and DELETE methods, which may not be
available in the client HTTP stack you are using. You should complain
to the authors of that stack that it is not a full HTTP implementation.
If that doesn't work, then there is a work-around by putting the
X_HTTP_METHOD_OVERRIDE header with the value of the method you want to
simulate. For example, to make curl do a POST, but use the PUT handler,
do:

 curl -v -v -d @changeset.osm -H "X_HTTP_METHOD_OVERRIDE: PUT" "http://server/api/0.6/changeset/create"

=head1 API calls

Here we will list the api calls :

=head2 Miscellaneous Capabilities: C<GET /api/capabilities>

This API call is meant to provide information about the capabilities
and limitations of the current API.

=head2 Response

Returns a XML document (content type C<text/xml>)

 <osm version="0.6" generator="OpenStreetMap server">
   <api>
     <version minimum="0.6" maximum="0.6"/>
     <area maximum="0.25"/>
     <tracepoints per_page="5000"/>
     <waynodes maximum="2000"/>
     <changesets maximum_elements="50000"/>
     <timeout seconds="300"/>
   </api>
 </osm>

Please note that actual returned values may change at any time and this
XML document only serves as an example.

=over

=item * Version minimum and maximum are the API call versions that the
server will accept.

=item * Area maximum is the maximum area in square degrees that can be
queried by API calls.

=item * Tracepoints per_page is the maximum number of points in a
single GPS trace. (Possibly incorrect)

=item * Waypoints maximum is the maximum number of nodes that a way may
contain.

=item * Changesets maximum is the maximum number of combined nodes,
ways and relations that can be contained in a changeset.

=back

=head2 Notes

=over

=item * Note that the URL is versionless. For convenience, the server
supports the request C</api/0.6/capabilities> too, such that clients
can use the same URL prefix C<http:/.../api/0.6> for all requests.

=back

=head2 Retrieving map data by bounding box: C<GET /api/0.6/map>

The following command returns:

=over

=item * All nodes that are inside a given bounding box and any
relations that reference them.

=item * All ways that reference at least one node that is inside a
given bounding box, any relations that reference them [the ways], and
any nodes outside the bounding box that the ways may reference.

=item * All relations that reference one of the nodes or ways included
due to the above rules. (Does B<not> apply recursively.)

=back

 GET /api/0.6/map?bbox=left,bottom,right,top

where:

=over

=item * C<I<left>> is the longitude of the left (westernmost) side of
the bounding box.

=item * C<I<bottom>> is the latitude of the bottom (southernmost) side
of the bounding box.

=item * C<I<right>> is the longitude of the right (easternmost) side of
the bounding box.

=item * C<I<top>> is the latitude of the top (northernmost) side of the
bounding box.

=back

Note that, while this command returns those relations that reference
the aforementioned nodes and ways, the reverse is not true: it does not
(necessarily) return all of the nodes and ways that are referenced by
these relations. This prevents unreasonably-large result sets. For
example, imagine the case where:

=over

=item * There is a relationship named "England" that references every
node in England.

=item * The nodes, ways, and relations are retrieved for a bounding box
that covers a small portion of England.

=back

While the result would include the nodes, ways, and relations as
specified by the rules for the command, including the "England"
relation, it would (fortuitously) I<not> include I<every> node and way
in England. If desired, the nodes and ways referenced by the "England"
relation could be retrieved by their respective IDs.

Also note that ways which intersect the bounding box but have no nodes
within the bounding box will not be returned.

=head2 Error codes

=over

=item HTTP status code 400 (Bad Request)

When any of the node/way/relation limits are crossed

=back

=over

=item HTTP status code 509 (Bandwidth Limit Exceeded)

"Error: You have downloaded too much data. Please try again later." See
Developer FAQ
(http://wiki.openstreetmap.org/wiki/Developer_FAQ#I.27ve_been_blocked_from_the_API_for_downloading_too_much._Now_what.3F).

=back

=head2 Changesets

To make it easier to identify related changes the concept of changesets
is introduced. Every modification of the standard OSM elements has to
reference an open changeset. A changeset may contain tags just like the
other elements. A recommended tag for changesets is the key C<comment
(http://wiki.openstreetmap.org/wiki/Key:comment)=*> with a short human
readable description of the changes being made in that changeset,
similar to a commit message in a revision control system. A new
changeset can be opened at any time and a changeset may referenced from
multiple API calls. Because of this it can be closed manually as the
server can't know when one changeset ends and another should begin. To
avoid stale open changesets a mechanism is implemented to automatically
close changesets upon one of the following three conditions:

=over

=item * More than 50.000 edits on a single changeset See more specific
limits (http://wiki.openstreetmap.org/wiki/API_v0.6#New_Limits)

=item * The changeset has been open for more than 24 hours

=item * There have been no changes/API calls related to a changeset in
1 hour (i.e. idle timeout)

=back

Changesets are specifically I<not> atomic - elements added within a
changeset will be visible to other users before the changeset is
closed. Given how many changes might be uploaded in one step it's not
feasible. Instead optimistic locking is used as described above.
Anything submitted to the server in a single request will be considered
atomically. To achieve transactionality for multiple changes there is
the new I<diff upload> API call.

Changesets facilitate the implementation of rollbacks. By providing
insight into the changes committed by a single person it becomes easier
to identify the changes made, rather than just rolling back a whole
region. Direct support for rollback will not be in the API, instead
they will be a form of reverse merging, where client can download the
changeset, examine the changes and then manipulate the API to obtain
the desired results. Rolling back a changeset can be be an extremely
complex process especially if the rollback conflicts with other changes
made in the mean time; we expect (hope) that in time, expert
applications will be created that make rollback on various levels
available to the average user.

To support easier usage, the server stores a bounding box for each
changeset and allows users to query changesets in an area. This will be
calculated by the server, since it needs to look up the relevant nodes
anyway. As an optimisation the server will create a buffer slightly
larger than the objects to avoid having to update the bounding box too
often. Client should note that if people make many small changes in a
large area they will be easily matched. In this case clients should
examine the changeset directly to see if it truly overlaps. A client
can expand the bounding box manually using an API call, which can be
useful when the client already knows the full extent of the data it is
about to upload.

It is not possible to delete changesets at the moment, even if they
don't contain any changes. The server may at a later time delete
changesets which are closed and which do not contain any changes. This
is not yet implemented.

=head2 Bounding box computation

This is how the API computes the bounding box associated with a
changeset:

=over

=item * Nodes: Any change to a node, including deletion, adds the
node's old and new location to the bbox.

=item * Ways: Any change to a way, including deletion, adds all of the
way's nodes to the bbox.

=item * Relations:

=back

=over

=item * adding or removing nodes or ways from a relation causes them to
be added to the changeset bounding box.

=item * adding a relation member or changing tag values causes all node
and way members to be added to the bounding box.

=item * this is similar to how the map call does things and is
reasonable on the assumption that adding or removing members doesn't
materially change the rest of the relation.


=back

=head2 Create: C<PUT /api/0.6/changeset/create>

The payload of a changeset creation request has to be one or more
C<changeset> elements optionally including an arbitrary number of tags.

 <osm>
   <changeset>
     <tag k="created_by" v="JOSM 1.61"/>
     <tag k="comment" v="Just adding some streetnames"/>
     ...
   </changeset>
   ...
 </osm>

If there are multiple C<changeset> elements in the XML the tags from
all of them are used, later ones overriding the earlier ones in case of
duplicate keys.

=head2 Response

The ID of the newly created changeset with a content type of
C<text/plain>

=head2 Error codes

=over

=item HTTP status code 400 (Bad Request)

When there are errors parsing the XML

=item HTTP status code 405 (Method Not Allowed)

If the request is not a HTTP PUT request

=back

=head2 Notes

Any number of possibly editor-specific, tags are allowed. An editor
might, for example, automatically include information about which
background image was used, or even a bit of internal state information
that will make it easier to revisit the changeset with the same editor
later, etc.

Clients I<should> include a C<created_by
(http://wiki.openstreetmap.org/wiki/Key:created_by)=*> tag. Clients are
advised to make sure that a C<comment
(http://wiki.openstreetmap.org/wiki/Key:comment)=*> is present, which
the user has entered. It is optional at the moment but this I<might>
change in later API versions. Clients I<should not> automatically
generate the comment tag, as this tag is for the end-user to describe
their changes. Clients I<may> add any other tags as they see fit.

=head2 Read: C<GET /api/0.6/changeset/#id>

Returns the changeset with the given C<id> in OSM-XML format.

 <osm>
   <changeset id="10" user="fred" uid="123" created_at="2008-11-08T19:07:39+01:00" open="true" min_lon="7.0191821" min_lat="49.2785426" max_lon="7.0197485" max_lat="49.2793101">
     <tag k="created_by" v="JOSM 1.61"/>
     <tag k="comment" v="Just adding some streetnames"/>
     ...
  </changeset>
 </osm>

=head2 Parameters

=over

=item id

The id of the changeset to retrieve

=back

=head2 Response

Returns the single changeset element containing the changeset tags with
a content type of C<text/xml>

=head2 Error codes

=over

=item HTTP status code 404 (Not Found)

When no changeset with the given id could be found

=back

=head2 Notes

=over

=item * The C<uid> might not be available for changesets auto generated
by the API v0.5 to API v0.6 transition?

=item * The bounding box attributes will be missing for an empty
changeset.

=item * The changeset bounding box is a rectangle that contains the
bounding boxes of all objects changed in this changeset. It is not
necessarily the smallest possible rectangle that does so.

=item * This API call only returns information about the changeset
itself but not the actual changes made to elements in this changeset.
To access this information use the I<download> API call.

=back

=head2 Update: C<PUT /api/0.6/changeset/#id>

For updating tags on the changeset, e.g. changeset C<comment
(http://wiki.openstreetmap.org/wiki/Key:comment)=foo
(http://wiki.openstreetmap.org/w/index.php?title=Tag:comment%3Dfoo&action=edit&redlink=1)>.

Payload should be an OSM document containing the new version of a
single changeset. Bounding box, update time and other attributes are
ignored and cannot be updated by this method. For updating the bounding
box see the I<expand_bbox> method.

 <osm>
   <changeset>
     <tag k="comment" v="Just adding some streetnames and a restaurant"/>
   </changeset>
 </osm>

=head2 Parameters

=over

=item id

The id of the changeset to update. The user issuing this API call has
to be the same that created the changeset

=back

=head2 Response

An OSM document containing the new version of the changeset with a
content type of C<text/xml>

=head2 Error codes

=over

=item HTTP status code 400 (Bad Request)

When there are errors parsing the XML

=item HTTP status code 404 (Not Found)

When no changeset with the given id could be found

=item HTTP status code 405 (Method Not Allowed)

If the request is not a HTTP PUT request

=item HTTP status code 409 (Conflict) - C<text/plain>

If the changeset in question has already been closed (either by the
user itself or as a result of the auto-closing feature). A message with
the format "C<The changeset #id was closed at #closed_at.>" is returned

Or if the user trying to update the changeset is not the same as the
one that created it

=back

=head2 Notes

Unchanged tags have to be repeated in order to not be deleted.

=head2 Close: C<PUT /api/0.6/changeset/#id/close>

Closes a changeset. A changeset may already have been closed without
the owner issuing this API call. In this case an error code is
returned.

=head2 Parameters

=over

=item id

The id of the changeset to close. The user issuing this API call has to
be the same that created the changeset.

=back

=head2 Response

Nothing is returned upon successful closing of a changeset (HTTP status
code 200)

=head2 Error codes

=over

=item HTTP status code 404 (Not Found)

When no changeset with the given id could be found

=item HTTP status code 405 (Method Not Allowed)

If the request is not a HTTP PUT request

=item HTTP status code 409 (Conflict) - C<text/plain>

If the changeset in question has already been closed (either by the
user itself or as a result of the auto-closing feature). A message with
the format "C<The changeset #id was closed at #closed_at.>" is returned

Or if the user trying to update the changeset is not the same as the
one that created it

=back

=head2 Download: C<GET /api/0.6/changeset/#id/download>

Returns the OsmChange (http://wiki.openstreetmap.org/wiki/OsmChange)
document describing all changes associated with the changeset.

=head2 Parameters

=over

=item id

The id of the changeset for which the OsmChange is requested.

=back

=head2 Response

The OsmChange XML with a content type of C<text/xml>.

=head2 Error codes

=over

=item HTTP status code 404 (Not Found)

When no changeset with the given id could be found

=back

=head2 Notes

=over

=item * The result of calling this may change as long as the changeset
is open.

=item * The elements in the OsmChange are sorted by timestamp and
version number.

=back

=head2 Expand Bounding Box: C<POST /api/0.6/changeset/#id/expand_bbox>

POSTing a XML document containing I<node> elements (these C<node>
elements have nothing to do with the I<Nodes> mentioned elsewhere in
this page, they are merely a container for I<lat> and I<lon>
attributes) that are to this location will cause the bounding box of
the changeset to expand to I<exactly> the smallest containing rectangle
of the points given and the bounding box automatically calculated by
the API. So this call can only I<increase> the size of the bounding box
and later additions to the changeset may override the expanded bounding
box.

The input document should look like this:

 <osm>
   <node lat=".." lon=".."/>
   <node lat=".." lon=".."/>
   ...
 </osm>

The I<osm> element may contain other elements than I<node>, but these
are ignored. The I<node> element may contain other attributes
(including I<id>) than lat and lon, but these are ignored as well.

This call is supported to give editors the chance to expand the
bounding box that the API automatically computes for the changeset.
There are cases where the editor will have extra knowledge that make it
advisable to flag a larger area as I<changed> than the API would guess
from the changes alone. This call may also be used before uploading a
large number of changes as a hint for the server which area will be
affected.

=head2 Parameters

=over

=item id

The id of the changeset for which the OsmChange is requested.

=back

=head2 Response

Returns the updated changeset containing with a content type of
C<text/xml>.

=head2 Error codes

=over

=item HTTP status code 404 (Not Found)

When no changeset with the given id could be found

=item HTTP status code 409 (Conflict) - C<text/plain>

If the changeset in question has already been closed (either by the
user itself or as a result of the auto-closing feature). A message with
the format "C<The changeset #id was closed at #closed_at.>" is returned

Or if the user trying to update the changeset is not the same as the
one that created it

=back

=head2 Notes

=over

=item * I don't know if there are really any advantages in issuing a
C<expand_bbox> call before a large chunk of changes is uploaded.

=item * As the reuse of C<node> as a XML element name is confusing and
the format of this call might change in a later API version.

=back

=head2 Query: C<GET /api/0.6/changesets>

This is an API method for querying changesets. It supports querying by
different criteria.

Where multiple queries are given the result will be those which match
all of the requirements. The contents of the returned document are the
changesets and their tags. To get the full set of changes associated
with a changeset, use the I<download> method on each changeset ID
individually.

Modification and extension of the basic queries above may be required
to support rollback and other uses we find for changesets.

=head2 Parameters

=over

=item bbox=min_lon,min_lat,max_lon,max_lat (W,S,E,N)

Find changesets within the given bounding box

=item user=#uid B<or> display_name=#name

Find changesets by the user with the given user id or display name.
Providing both is an error.

=item time=T1

Find changesets I<closed> after T1

=item time=T1,T2

Find changesets that were I<closed> after T1 and I<created> before T2

=item open

Only finds changesets that are still I<open> but excludes changesets
that are closed or have reached the element limit for a changeset
(50.000 at the moment)

=item closed

Only finds changesets that are I<closed> or have reached the element
limit

=back

Time format: Anything that this Ruby function
(http://www.ruby-doc.org/core/classes/DateTime.html#M002825) will
parse. The default str is
E<acirc>E<128>E<153>-4712-01-01T00:00:00+00:00E<acirc>E<128>E<153>;
this is Julian Day Number day 0.

=head2 Response

Returns a list of all changeset ordered by creation date. The
C<E<lt>osmE<gt>> element may be empty if there were no results for the
query. The response is send with a content type of C<text/xml>.

=head2 Error codes

=over

=item HTTP status code 400 (Bad Request) - C<text/plain>

On misformed parameters. A text message explaining the error is
returned. In particular, trying to provide both the UID and display
name as user query parameters will result in this error.

=item HTTP status code 404 (Not Found)

When no user with the given C<uid> or C<display_name> could be found.

=back

=head2 Notes

=over

=item * Only changesets by public users are returned.

=item * I'm not sure if the time query makes sense as it is implemented
now. The original documentation for this feature states:

=over

=item * One-sided to query changesets where the start time is after the
given time.

=item * Bounded (?time=T1,T2) to query where the start time is between
the given times.

=back

=item * Returns at most 100 changesets

=back

=head2 Diff upload: C<POST /api/0.6/changeset/#id/upload>

With this API call files in the OsmChange
(http://wiki.openstreetmap.org/wiki/OsmChange) format can be uploaded
to the server. This is guaranteed to be running in a transaction. So
either all the changes are applied or none.

To upload an OSC file it has to conform to the OsmChange
(http://wiki.openstreetmap.org/wiki/OsmChange) specification with the
following additions:

=over

=item * each element must carry a I<changeset> and a I<version>
attribute, except when you are creating an element where the version is
not required as the server sets that for you. The I<changeset> must be
the same as the changeset ID being uploaded to.

=back

=over

=item * a E<lt>deleteE<gt> block in the OsmChange document may have an
I<if-unused> attribute (the value of which is ignored). If this
attribute is present, then the delete operation(s) in this block are
conditional and will only be executed if the object to be deleted is
not used by another object. Without the I<if-unused>, such a situation
would lead to an error, and the whole diff upload would fail.

=back

=head2 Parameters

=over

=item id

The ID of the changeset this diff belongs to.

=item POST data

The OsmChange file data

=back

=head2 Response

If a diff is successfully applied a XML (content type C<text/xml>) is
returned in the following format

 <diffResult generator="OpenStreetMap Server" version="0.6">
   <node|way|relation old_id="#" new_id="#" new_version="#"/>
   ...
 </diffResult>

with one element for every element in the upload. Note that this can be
counter-intuitive when the same element has appeared multiple times in
the input then it will appear multiple times in the output.

Attribute

create

modify

delete

old_id

same as uploaded element.

new_id

new ID

same as uploaded

not present

new_version

new version

not present

=head2 Error codes

=over

=item HTTP status code 400 (Bad Request) - C<text/plain>

When there are errors parsing the XML. A text message explaining the
error is returned.

When an placeholder ID is missing or not unique

=item HTTP status code 405 (Method Not Allowed)

If the request is not a HTTP POST request

=item HTTP status code 409 (Conflict) - C<text/plain>

If the changeset in question has already been closed (either by the
user itself or as a result of the auto-closing feature). A message with
the format "C<The changeset #id was closed at #closed_at.>" is returned

If, while uploading, the max. size of the changeset is exceeded. A
message with the format "C<The changeset #id was closed at
#closed_at.>" is returned

Or if the user trying to update the changeset is not the same as the
one that created it

Or if the diff contains elements with changeset IDs which don't match
the changeset ID that the diff was uploaded to

Any of the error codes that could occur an a create, update or delete
operation for one of the elements

See the according sections in this page

=back

=head2 Notes

=over

=item * Processing stops at the first error, so if there are multiple
conflicts in one diff upload, only the first problem is reported.

=item * There is currently no limit in the diff size but this will
probably be changed later.

=back

=head2 Changeset summary

The procedure for successful creation of a changeset is summarized in
the following picture:

OSM API0.6 Changeset successful creation V0.1.png
(http://wiki.openstreetmap.org/wiki/File:OSM_API0.6_Changeset_successful_creation_V0.1.png)

=head2 Elements

There are create, read, update and delete calls for all of the three
basic elements in OpenStreetMap (I<Nodes>, I<Ways> and I<Relations>).
These calls are very similar except for the payload and a few special
error messages so they are documented only once.

=head2 Create: C<PUT /api/0.6/[node|way|relation]/create>

Creates a new element of the specified type. Note that the entire
request should be wrapped in a

 <osm>...</osm>

element.

A Node:

 <osm>
  <node changeset="12" lat="..." lon="...">
    <tag k="note" v="Just a node"/>
    ...
  </node>
 </osm>

A Way:

 <osm>
  <way changeset="12">
    <tag k="note" v="Just a way"/>
    ...
    <nd ref="123"/>
    <nd ref="4345"/>
    ...
  </way>
 </osm>

A Relation:

 <osm>
  <relation changeset="12">
    <tag k="note" v="Just a relation"/>
    ...
    <member type="node" role="stop" ref="123"/>
    <member type="way" ref="234"/>
  </relation>
 </osm>

If multiple elements are provided only the first is created. The rest
is discarded (this behaviour differs from changeset creation).

=head2 Response

The ID of the newly created element (content type is C<text/plain>)

=head2 Error codes

=over

=item HTTP status code 400 (Bad Request) - C<text/plain>

When there are errors parsing the XML. A text message explaining the
error is returned.

When a changeset ID is missing (unfortunately the error messages are
not consistent)

When a node is outside the world

When there are too many nodes for a way

=item HTTP status code 405 (Method Not Allowed)

If the request is not a HTTP PUT request

=item HTTP status code 409 (Conflict) - C<text/plain>

If the changeset in question has already been closed (either by the
user itself or as a result of the auto-closing feature). A message with
the format "C<The changeset #id was closed at #closed_at.>" is returned

Or if the user trying to update the changeset is not the same as the
one that created it

=item HTTP status code 412 (Precondition Failed)

When a way has nodes that do not exist or are not visible (i.e.
deleted): "C<Way #{id} requires the nodes with id in (#{missing_ids}),
which either do not exist, or are not visible.>"

When a relation has elements that do not exist or are not visible:
"C<Relation with id #{id} cannot be saved due to #{element} with id
#{element.id}>"

=back

=head2 Notes

=over

=item * This updates the bounding box of the changeset.

=item * The I<role> attribute for relations is optional. An empty
string is the default.

=back

=head2 Read: C<GET /api/0.6/[node|way|relation]/#id>

Returns the XML representation of the element.

=head2 Response

XML representing the element, wrapped in an C<E<lt>osmE<gt>> element:

 <osm>
  <node id="123" lat="..." lon="..." version="142" changeset="12" user="fred" uid="123" visible="true" timestamp="2005-07-30T14:27:12+01:00">
    <tag k="note" v="Just a node"/>
    ...
  </node>
 </osm>

=head2 Error codes

=over

=item HTTP status code 404 (Not Found)

When no element with the given id could be found

=item HTTP status code 410 (Gone)

If the element has been deleted

=back

=head2 Update: C<PUT /api/0.6/[node|way|relation]/#id>

Updates data from a preexisting element. A full representation of the
element as it should be after the update has to be provided. So any
tags that remain unchanged have to be in the update as well. A version
number has to be provided as well.

=head2 Response

Returns the new version number with a content type of C<text/plain>.

=head2 Error codes

=over

=item HTTP status code 400 (Bad Request) - C<text/plain>

When there are errors parsing the XML. A text message explaining the
error is returned. This can also happen if you forget to pass the
Content-Length header.

When a changeset ID is missing (unfortunately the error messages are
not consistent)

When a node is outside the world

When there are too many nodes for a way

When the version of the provided element does not match the current
database version of the element

=item HTTP status code 409 (Conflict) - C<text/plain>

If the changeset in question has already been closed (either by the
user itself or as a result of the auto-closing feature). A message with
the format "C<The changeset #id was closed at #closed_at.>" is returned

Or if the user trying to update the changeset is not the same as the
one that created it

=item HTTP status code 404 (Not Found)

When no element with the given id could be found

=item HTTP status code 412 (Precondition Failed)

When a way has nodes that do not exist or are not visible (i.e.
deleted): "C<Way #{id} requires the nodes with id in (#{missing_ids}),
which either do not exist, or are not visible.>"

When a relation has elements that do not exist or are not visible:
"C<Relation with id #{id} cannot be saved due to #{element} with id
#{element.id}>"

=back

=head2 Notes

=over

=item * This updates the bounding box of the changeset.

=back

=head2 Delete: C<DELETE /api/0.6/[node|way|relation]/#id>

Expects a valid XML representation of the element to be deleted.

For example:

 <osm>
  <node id="..." version="..." changeset="..."/>
 </osm>

Where the node ID in the XML must match the ID in the URL, the version
must match the version of the element you downloaded and the changeset
must match the ID of an open changeset owned by the current
authenticated user. It is allowed, but not necessary, to have tags on
the element except for lat/long tags which are required, see
http://web.archiveorange.com/archive/v/wQWIbRy3o8HjRNYaSim9
(http://web.archiveorange.com/archive/v/wQWIbRy3o8HjRNYaSim9) and also
tested to still hold on 2011-05-30, without lat+lon the server gives
400 Bad request.

=head2 Response

Returns the new version number with a content type of C<text/plain>.

=head2 Error codes

=over

=item HTTP status code 400 (Bad Request) - C<text/plain>

When there are errors parsing the XML. A text message explaining the
error is returned.

When a changeset ID is missing (unfortunately the error messages are
not consistent)

When a node is outside the world

When there are too many nodes for a way

When the version of the provided element does not match the current
database version of the element

=back

=over

=item HTTP status code 404 (Not Found)

When no element with the given id could be found

=back

=over

=item HTTP status code 409 (Conflict) - C<text/plain>

If the changeset in question has already been closed (either by the
user itself or as a result of the auto-closing feature). A message with
the format "C<The changeset #id was closed at #closed_at.>" is returned

Or if the user trying to update the changeset is not the same as the
one that created it

=back

=over

=item HTTP status code 410 (Gone)

If the element has been already been deleted

=back

=over

=item HTTP status code 412 (Precondition Failed)

When a node is still used by a way: C<Node #{id} is still used by way
#{way.id}.>

When a node is still member of a relation: C<Node #{id} is still used
by relation #{relation.id}.>

When a way is still member of a relation: C<Way #{id} still used by
relation #{relation.id}.>

When a relation is still member of another relation: C<The relation
#{id} is used in relation #{relation.id}.>

=back

=head2 Notes

=over

=item * In earlier API versions no payload was required. It is needed
now because of the need for changeset IDs and version numbers.

=back

=head2 History: C<GET /api/0.6/[node|way|relation]/#id/history>

Retrieves all old versions of an element. The old versions are not
guaranteed to be ordered in any way.

=head2 Error codes

=over

=item HTTP status code 404 (Not Found)

When no element with the given id could be found

=back

=head2 Version: C<GET /api/0.6/[node|way|relation]/#id/#version>

Retrieves a specific version of the element.

=head2 Error codes

=over

=item HTTP status code 404 (Not Found)

When no element with the given id could be found

=back

=head2 Multi fetch: C<GET /api/0.6/[nodes|ways|relations]>

Allows a user to fetch multiple elements at once.

=head2 Parameters

=over

=item [nodes|ways|relations]=comma separated list

The parameter has to be the same in the URL (e.g.
/api/0.6/nodes?nodes=123,456,789)

=back

=head2 Error codes

=over

=item HTTP status code 400 (Bad Request)

On a malformed request (parameters missing or wrong)

=item HTTP status code 404 (Not Found)

If one of the elements could not be found

=item HTTP status code 414 (Request-URI Too Large)

If the URI was too long (How long is too long?)

=back

=head2 Relations for Element: C<GET /api/0.6/[node|way|relation]/#id/relations>

Returns a XML document containing all (not deleted) relations in which
the given element is used.

=head2 Notes

=over

=item * There is no error if the element does not exist.

=item * If the element does not exist or it isn't used in any relations
an empty XML document is returned (apart from the C<E<lt>osmE<gt>>
elements)

=back

=head2 Ways for Node: C<GET /api/0.6/node/#id/ways>

Returns a XML document containing all the (not deleted) ways in which
the given node is used.

=head2 Notes

=over

=item * There is no error if the node does not exist.

=item * If the node does not exist or it isn't used in any ways an
empty XML document is returned (apart from the C<E<lt>osmE<gt>>
elements)

=back

=head2 Full: C<GET /api/0.6/[way|relation]/#id/full>

This API call retrieves a way or relation and all other elements
referenced by it

=over

=item * For a way, it will return the way specified plus the full XML
of all nodes referenced by the way.

=item * For a relation, it will return the following:

=over

=item * The relation itself

=item * All nodes, ways, and relations that are members of the relation

=item * Plus all nodes used by ways from the previous step

=item * The same recursive logic is not applied to relations. This
means: If relation r1 contains way w1 and relation r2, and w1 contains
nodes n1 and n2, and r2 contains node n3, then a "full" request for r1
will give you r1, r2, w1, n1, and n2. Not n3.

=back

=back

=head2 Error codes

=over

=item HTTP status code 404 (Not Found)

When no element with the given id could be found

=item HTTP status code 410 (Gone)

If the element has been deleted

=back

=head2 GPS Traces

=head2 Retrieving GPS points

The following command returns, in GPX format, the GPS track points that
are inside a given bounding box.

 GET /api/0.6/trackpoints?bbox=left,bottom,right,top&page=pageNumber

where:

=over

=item * C<I<left>>, C<I<bottom>>, C<I<right>>, and C<I<top>> are used
the same way as they are in the command to retrieve nodes, ways, and
relations.

=item * C<I<pageNumber>> specifies which group of 5,000 points, or
I<page>, to return. Since the command does not return more than 5,000
points at a time, this parameter must be
incrementedE<acirc>E<128>E<148>and the command sent again (using the
same bounding box)E<acirc>E<128>E<148>in order to retrieve all of the
points for a bounding box that contains more than 5,000 points. When
this parameter is 0 (zero), the command returns the first 5,000 points;
when it is 1, the command returns points
5,001E<acirc>E<128>E<147>10,000, etc.

=back

=head2 Examples

Retrieve the first 5,000 points for a bounding box:

 http://api.openstreetmap.org/api/0.6/trackpoints?bbox=0,51.5,0.25,51.75&page=0

Retrieve the next 5,000 points (points 5,001E<acirc>E<128>E<147>10,000)
for the same bounding box:

 http://api.openstreetmap.org/api/0.6/trackpoints?bbox=0,51.5,0.25,51.75&page=1

=head2 Uploading Traces

You can upload a GPX file or archive of GPX files through the API:

 POST /api/0.6/gpx/create

This is the only API call using the POST method. It expects the
following POST parameters in a multipart/form-data HTTP message:

parameter

description

file

The GPX file containing the track points. Note that for successful
processing, the file must contain trackpoints (E<lt>trkptE<gt>), not
only waypoints, and the trackpoints must have a valid timestamp. Since
the file is processed asynchronously, the call will complete
successfully even if the file cannot be processed. The file may also be
a .tar, .tar.gz or .zip containing multiple gpx files, although it will
appear as a single entry in the upload log.

description

The trace description.

tags

A string containing tags for the trace.

public

1 if the trace is public, 0 if not. This exists for backwards
compatibility only - the visibility parameter should now be used
instead. This value will be ignored if visibility is also provided.

visibility

One of the following: private, public, trackable, identifiable (for
explanations see OSM trace upload page
(http://www.openstreetmap.org/traces/mine) or Visibility of GPS traces
(http://wiki.openstreetmap.org/wiki/Visibility_of_GPS_traces))

HTTP basic authentication is required.

=head2 Downloading Trace Metadata

You access a GPX file's details and download the full file:

 GET /api/0.6/gpx/<id>/details
 GET /api/0.6/gpx/<id>/data

HTTP basic authentication is required, although theoretically these
calls should be allowed without authentication if the trace is marked
public. If the trace is not public, only the owner may access the data.

Example "details" response:

 <?xml version="1.0" encoding="UTF-8"?>
 <osm version="0.6" generator="OpenStreetMap server">
   <gpx_file id="836619" name="track.gpx" lat="52.0194" lon="8.51807" 
             user="Hartmut Holzgraefe" visibility="public" pending="false"  
             timestamp="2010-10-09T09:24:19Z">
     <description>PHP upload test</description>
     <tag>test</tag>
     <tag>php</tag>
   </gpx_file>
 </osm>

The "data" response will be the exact file uploaded.

You can also get a list of all the GPX traces for the authenticated
user using:

 GET /api/0.6/user/gpx_files

=head2 Methods for User Data

Unless noted otherwise, all user-specific API calls require
authentication and operate on the currently authenticated user account.
That's why they don't normally have an explicit "username" parameter.

=head2 Details

You can get the home location and the displayname of the user, by using

 GET /api/0.6/user/details

this returns an XML document of the from

 <osm version="0.6" generator="OpenStreetMap server">
  <user display_name="Max Muster" account_created="2006-07-21T19:28:26Z" id="1234">
    <home lat="49.4733718952806" lon="8.89285988577866" zoom="3"/>
    <description>The description of your profile</description>
    <languages>
      <lang>de-DE</lang>
      <lang>de</lang>
      <lang>en-US</lang>
      <lang>en</lang>
    </languages>
  </user>
 </osm>

=head2 Preferences

The OSM server supports storing arbitrary user preferences. This can be
used by editors, for example, to offer the same configuration wherever
the user logs in, instead of a locally-stored configuration.

You can retrieve the list of current preferences using

 GET /api/0.6/user/preferences

this returns an XML document of the form

  <osm version="0.6" generator="OpenStreetMap server">
    <preferences>
       <preference k="somekey" v="somevalue" />
       ...
    </preferences>
  </osm>

The same structure can be used to upload preferences (using the PUT
method instead of GET). All existing preferences are replaced by the
newly uploaded set.

Also possible is to PUT a single preference using

 PUT /api/0.6/user/preferences/[your_key] (without the brackets)

in this instance, the payload of the request should only contain the
value of the preference, i.e. not XML formatted.

The PUT call returns HTTP response code 406 (not acceptable) if the
same key occurs more than once, and code 413 (request entity too large)
if you try to upload more than 150 preferences at once. The sizes of
the key and value are limited to 255 characters.

=head1 When NOT to use the API

For bulk upload scripts or data modification, the API may not be the
proper mechanism. The modern version of creating a bulk upload or
modification script is to build a change set, load it into an editor
like JOSM, and verify the work prior to commit. You can also use the
API to upload a change set in an atomic manner. See also:
http://wiki.openstreetmap.org/wiki/Change_File_Formats
(http://wiki.openstreetmap.org/wiki/Change_File_Formats)

=head1 Further Reading

=over

=item * People making clients, see API v0.6
(Archive)#Changes_in_related_software
(http://wiki.openstreetmap.org/wiki/API_v0.6_(Archive)#Changes_in_related_software)

=item * People interested in the DB see API v0.6
(Archive)#Database_improvements
(http://wiki.openstreetmap.org/wiki/API_v0.6_(Archive)#Database_improvements)

=item * Status of routing file API v0.6/Command Overview
(http://wiki.openstreetmap.org/wiki/API_v0.6/Command_Overview)

=item * possible API errors
(http://wiki.openstreetmap.org/wiki/API_v0.6/APIError)

=back

Retrieved from "http://wiki.openstreetmap.org/wiki/API_v0.6
(http://wiki.openstreetmap.org/wiki/API_v0.6)"

Category (http://wiki.openstreetmap.org/wiki/Special:Categories): OSM
API (http://wiki.openstreetmap.org/wiki/Category:OSM_API)

=head2 Personal tools

=over

=item * Log in / create account
(http://wiki.openstreetmap.org/w/index.php?title=Special:UserLogin&returnto=API_v0.6)

=back

=head2 Namespaces

=over

=item * Page (http://wiki.openstreetmap.org/wiki/API_v0.6)

=item * Discussion (http://wiki.openstreetmap.org/wiki/Talk:API_v0.6)

=back

=head2 Variants (http://wiki.openstreetmap.org/wiki/API_v0.6#)

=head2 Views

=over

=item * Read (http://wiki.openstreetmap.org/wiki/API_v0.6)

=item * View source
(http://wiki.openstreetmap.org/w/index.php?title=API_v0.6&action=edit)

=item * View history
(http://wiki.openstreetmap.org/w/index.php?title=API_v0.6&action=history)

=back

=head2 Actions (http://wiki.openstreetmap.org/wiki/API_v0.6#)

=head2 Search

Search

(http://wiki.openstreetmap.org/wiki/Main_Page)

=head2 Recent changes

=over

=item * Recent changes
(http://wiki.openstreetmap.org/wiki/Special:RecentChanges)

=back

=head2 Navigation

=over

=item * Main Page (http://wiki.openstreetmap.org/wiki/Main_Page)

=item * The map (http://www.openstreetmap.org/)

=item * Mapping projects
(http://wiki.openstreetmap.org/wiki/Mapping_projects)

=item * Map Features (http://wiki.openstreetmap.org/wiki/Map_Features)

=item * Help (http://wiki.openstreetmap.org/wiki/Help:Contents)

=item * Blog (http://wiki.openstreetmap.org/wiki/OSM_Blogs)

=item * Shop (http://wiki.openstreetmap.org/wiki/Merchandise)

=item * Donations (http://wiki.openstreetmap.org/wiki/Donations)

=item * Impressum
(http://wiki.openstreetmap.org/wiki/OpenStreetMap:Impressum)

=back

=head2 Toolbox

=over

=item * What links here
(http://wiki.openstreetmap.org/wiki/Special:WhatLinksHere/API_v0.6)

=item * Related changes
(http://wiki.openstreetmap.org/wiki/Special:RecentChangesLinked/API_v0.6)

=item * Special pages
(http://wiki.openstreetmap.org/wiki/Special:SpecialPages)

=item * Printable version
(http://wiki.openstreetmap.org/w/index.php?title=API_v0.6&printable=yes)

=item * Permanent link
(http://wiki.openstreetmap.org/w/index.php?title=API_v0.6&oldid=648881)

=back

=over

=item * This page was last modified on 21 June 2011, at 12:13.

=item * Content is available under Creative Commons
Attribution-ShareAlike 2.0 license
(http://wiki.openstreetmap.org/wiki/OpenStreetMap_License).

=back

=over

=item * Privacy policy
(http://wiki.openstreetmap.org/wiki/Privacy_Policy)

=item * About OpenStreetMap Wiki
(http://wiki.openstreetmap.org/wiki/About)

=item * Disclaimers
(http://wiki.openstreetmap.org/wiki/OpenStreetMap:General_disclaimer)

=back

=over

=item * Powered by MediaWiki (http://www.mediawiki.org/)

=item * Creative Commons Attribution-ShareAlike 2.0 license
(http://creativecommons.org/licenses/by-sa/2.0/)

=back

=cut

#Pod::HTML2Pod conversion notes:
#From file OpenStreetMapAPIv0.6.html
# 106087 bytes of input
#Sat Jul 16 08:26:38 2011 mdupont
# No a_name switch not specified, so will not try to render <a name='...'>
# Will try to render <a href='...'>
# Untranslatable link: "./OpenStreetMapAPIv0.6_files/OpenStreetMapAPIv0.6.html"
